services:
  carrental.webapi:
    image: carrental.webapi
    build:
      context: .
      dockerfile: CarRental.WebApi/Dockerfile
    ports:
      - "8080:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresSQL=Host=db;Port=5432;Database=CarRental;Username=postgres;Password=postgres
    depends_on:
      - db
  
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: CarRental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: